using AmongUs.GameOptions;
using System;
using System.Collections;
using TOHE.Roles.Core;
using TOHE.Roles.Core.AssignManager;

namespace TOHE.Modules;

/// <summary>Recipient presentation is separate from assigning a custom ghost or recording a death.</summary>
internal static class GhostRoleView
{
    private static PlayerControl localExile;

    internal static bool SuppressNativeAssignment(PlayerControl player) => player != null && player == localExile;

    // Keep this decision free of RPCs and death side effects, so recovery and Phantom can reuse it.
    internal static RoleTypes Resolve(bool self, bool targetImpostor, bool targetDesync, bool seerKiller, bool customGhost)
    {
        if (customGhost) return self ? RoleTypes.GuardianAngel : RoleTypes.CrewmateGhost;
        return self && (targetImpostor || targetDesync) || !seerKiller && targetImpostor
            ? RoleTypes.ImpostorGhost
            : RoleTypes.CrewmateGhost;
    }

    internal static RoleTypes ForRecipient(PlayerControl target, PlayerControl seer) => Resolve(
        target.PlayerId == seer.PlayerId,
        target.Is(Custom_Team.Impostor), target.HasDesyncRole(),
        seer.Is(Custom_Team.Impostor) || seer.HasDesyncRole(), target.HasGhostRole());

    internal static void AssignCustomGhost(PlayerControl target)
    {
        try
        {
            GhostRoleAssign.GhostAssignPatch(target);
            target.SyncSettings();
        }
        catch (Exception error)
        {
            Logger.Warn($"Error assigning custom ghost: {error}", "GhostRoleView");
        }
    }

    internal static void Publish(PlayerControl target)
    {
        var context = OfficialSessionContext.Capture();
        var netId = target.NetId;
        var ownerId = target.OwnerId;
        var views = Main.AllPlayerControls
            .Where(seer => seer != null && seer.Data != null && !seer.Data.Disconnected && seer.GetClientId() >= 0)
            .Select(seer => (Seer: seer, ClientId: seer.GetClientId(), Role: ForRecipient(target, seer))).ToArray();
        var barrier = CustomRpcTransport.CaptureBarrier();
        if (barrier.IsComplete) SendViews();
        else Main.Instance.StartCoroutine(WaitAndPublish());

        bool Current() => !barrier.IsCancelled && context.IsCurrent() && AmongUsClient.Instance.AmHost
            && target != null && target.Data != null && target.Data.IsDead
            && target.NetId == netId && target.OwnerId == ownerId && Main.AllPlayerControls.Contains(target)
            && CustomWinnerHolder.WinnerTeam == CustomWinner.Default;

        void SendViews()
        {
            if (!Current()) return;
            foreach (var (seer, clientId, role) in views)
            {
                if (!Current()) return;
                if (seer == null || seer.Data == null || seer.Data.Disconnected || seer.GetClientId() != clientId
                    || !Main.AllPlayerControls.Contains(seer)) continue;
                target.RpcSetRoleDesync(role, clientId);
            }
        }

        IEnumerator WaitAndPublish()
        {
            // The death remains local and immediate. Its metadata must be sent from
            // the native queue before recipients install their native ghost view.
            while (!barrier.IsComplete)
            {
                if (!Current()) yield break;
                yield return null;
            }
            SendViews();
        }
    }

    internal static void Exile(PlayerControl target, bool susceptible)
    {
        if (target == null || target.Data == null || !AmongUsClient.Instance.AmHost) return;

        // Recovery may repeat this request for an already dead player. Never rerun Die,
        // ejection statistics, pet removal or custom ghost selection for that request.
        if (!target.Data.IsDead)
        {
            if (susceptible && target.Is(CustomRoles.Susceptible))
                TOHE.Roles.AddOns.Common.Susceptible.CallEnabledAndChange(target);

            var previous = localExile;
            localExile = target;
            try
            {
                // Keep all native local death effects, but suppress the synchronous
                // RpcSetRole generated by RoleManager.AssignRoleOnDeath below.
                target.Exiled();
            }
            finally
            {
                localExile = previous;
            }
            AssignCustomGhost(target);
            if (target.HasGhostRole()) GhostRoleAssign.CreateGAMessage(target);
        }
        Publish(target);
    }
}
