<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LocalAmongUsPath Condition="'$(LocalAmongUsPath)' == ''">D:/Game/20260818/Itch</LocalAmongUsPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Modules/ModRegistration.cs" />
    <Compile Include="../../../Patches/ModRegistrationPatch.cs" />
    <Compile Include="PluginLifecycle.cs" />
    <Reference Include="$(LocalAmongUsPath)/BepInEx/interop/*.dll" Private="false" />
    <Reference Include="$(LocalAmongUsPath)/BepInEx/core/BepInEx.Core.dll" Private="false" />
    <Reference Include="$(LocalAmongUsPath)/BepInEx/core/0Harmony.dll" Private="false" />
    <Reference Include="$(LocalAmongUsPath)/BepInEx/core/BepInEx.Unity.IL2CPP.dll" Private="false" />
    <Reference Include="$(LocalAmongUsPath)/BepInEx/core/Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="$(LocalAmongUsPath)/BepInEx/core/Il2CppInterop.Common.dll" Private="false" />
  </ItemGroup>
</Project>
