<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Modules/OptionItem/*.cs" Link="Production/OptionItem/%(Filename)%(Extension)" />
    <Compile Include="../../Modules/OptionSaver.cs" Link="Production/OptionSaver.cs" />
    <Compile Include="../../Modules/PresetSharing.cs" Link="Production/PresetSharing.cs" />
  </ItemGroup>
</Project>
